M48
; DRILL file KiCad 10.0.5 date 2026-09-06T03:15:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-06T03:15:20+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X83.695Y-9.11
X83.695Y-14.89
T2
X3.0Y-3.0
X3.0Y-57.0
X87.0Y-3.0
X87.0Y-57.0
M30
